### ISSUE TITLE
Does not work with Craft CMS 2.6.2958

### ISSUE THREAD

**Issue by marzepani** [born05/craft-assetusage#1]
Adding the `Usage` table column results in an error. CP notification: **An unknown error occurred.**

Browser console: Failed to load resource: the server responded with a status of 500 (Internal Server Error)

PS: Thank you for your efforts. I love the concept and I would love to use this plugin. 👍

**Comment by roelvanhintum** [comment]
Should be fixed. Turns out SuperTable was needed. Now it's optional.
