### ISSUE TITLE
column not showing

### ISSUE THREAD

**Issue by colorao** [born05/craft-assetusage#15]
Hi.
Just installed the plugin.
It appears as installed and enabled, but I cannot see the column in the asset section.
 Am I missing something?
Some other configuration is needed?

Windows 10.
PHP 7.3.1
Craft PRO 3.0.31

**Comment by roelvanhintum** [comment]
Hi @colorao, you should click the little cog icon (in the bar left of your assets) and add the column. The plugin makes it available, but doesn't force it.

**Comment by colorao** [comment]
That is
Thank you so much !!


Un saludo



Pablo Fernández
pablo.fernandez@colorao.es
+34 685 108 325



www.colorao.es
+34 91 899 51 56
