### ISSUE TITLE
Show where assets are being used

### ISSUE THREAD

**Issue by sm9** [born05/craft-assetusage#16]
I've got some assets that are listed as being 'Used 1 time', but I can't figure out which entries are using them. It would be nice to be able to hover over the 'Used 1 time' text and see an alt tag or tooltip that outputted the entry IDs where the asset was used. I'm not a developer so I can't submit a pull request or anything, so this is just a feature request. :) Thanks.

**Comment by roelvanhintum** [comment]
Hi @sm9, the problem with this is that sometimes the id is a Matrix or SuperTable id. It doesn't have to be an entry.

For now, you could look in the "relations" database table for sourceId's and targetId's that match your asset's id.

**Comment by sm9** [comment]
Hi @roelvanhintum, thanks for explaining and I'll try the workaround looking at that table.

**Comment by saschapi** [comment]
I'm not sure if I understand. Shouldn't you be able to get the entry id by the Matrix? I absolutely agree that this would be a very very useful feature. As is, it is just saying "do not delete this". The information where it is used is crucial for any decision for the editor.

**Comment by roelvanhintum** [comment]
@saschapi That is true, it is possible to retrieve the entry id. It would just involve more complex queries for every asset.
There are some plugins that do not support relations and are not counted. So please be careful with deleting assets based on the usage.
