### ISSUE TITLE
3.2 Compatible? 

### ISSUE THREAD

**Issue by jan-dh** [born05/craft-assetusage#17]
I'm trying this plugin on Craft 3.2.10 but I can't see a visual queue as to what assets are being used or not. Could this have anything to do with the new pagination method introduced in 3.2?

**Comment by roelvanhintum** [comment]
@jan-dh just tested on Craft 3.2.10 without any issues. Did you add the "Usage" column in the `admin/asset` sprocket menu?

**Comment by roelvanhintum** [comment]
I've just added some setup explanation to the readme.

**Comment by jan-dh** [comment]
Perfect! works like a charm
