### ISSUE TITLE
Take assets referenced by SEO-plugin into account

### ISSUE THREAD

**Issue by ClemensSchneider** [born05/craft-assetusage#18]
I know, you are mentioning the SEO-plugin (https://github.com/ethercreative/seo) as not being supported, because referenced assets are not stored in the relation-table.

For a recent asset-cleanup for our website, I needed to determine all assets in use an came up with a query like the following (where the field-name is already known):

``` sql
SELECT CAST(SUBSTRING(field_caseSeo, LOCATE('imageId":"', field_caseSeo) + 10) AS SIGNED INTEGER) AS id FROM content WHERE field_caseSeo REGEXP 'imageId":"'
```

This way, I was able to extract the referenced ID (at least the first - there are possibly two of them for facebook and twitter) from the seo-field contents.

Maybe this could be a start for tackling this:
- get all fields of type `ether\seo\fields\SeoField`
- get possibly referenced asset-ids from these fields
- take these into account when calculating usage-count in asset-list

Thanks for your efforts put into this plugin!

**Comment by roelvanhintum** [comment]
@ClemensSchneider thanks, looks like a great feature!
I'll look into this.
