### ISSUE TITLE
False positives / 3.2 compatibility

### ISSUE THREAD

**Issue by darylknight** [born05/craft-assetusage#19]
I just tried this on a small project with 4 pages where I know which images are being used and which aren't. The placeholder images I used at the start of the project are shown as being used 8 times, but I've just run through the pages on the site and I can see they aren't used anymore.
I'd guess this is either something to do with the plugin looking at old revisions or drafts.

**Comment by roelvanhintum** [comment]
@darylknight it could be that old revisions keep relations until deleted. Craft uses soft deletes since craft 3.1 and up. The plugin just counts records in the relations table.
