### ISSUE TITLE
Craft Plugin Store release does not include latest commits

### ISSUE THREAD

**Issue by daltonrooney** [born05/craft-assetusage#21]
Running ./craft assetusage/default/delete-unused from the console results in an error: 
Unknown command: assetusage/default/delete-unused

When I simply run ./craft and get a list of all available commands, there's nothing listed for assetusage

Cheers.

**Comment by daltonrooney** [comment]
Update: for some reason, the version in the Craft Plugin Store, even though it's listed as version 2.0.1, does not include the latest commits. I downloaded straight from the master repo and installed manually and it seems to be working correctly from there.

**Comment by roelvanhintum** [comment]
@daltonrooney sorry about that, just released it in 2.1.0
When i wrote the commands i was hesitant about releasing them, because damage can be done when using some unsupported plugins for assets.

**Comment by daltonrooney** [comment]
Thanks, I appreciate it. I've actually been modifying the query to do things like sort by date and limit the number of results before deleting, it's been really helpful. The way you wrote the console controller made it very easy to understand!

**Comment by roelvanhintum** [comment]
@daltonrooney, thank you! If you have any improvements let me know or make a pull-request.
