### ISSUE TITLE
Feature request: Add new column 'Current usage'

### ISSUE THREAD

**Issue by Friksel** [born05/craft-assetusage#22]
First; great plugin, very useful. It's nice to see if assets are in use or could safely be removed.

That said; the Usage column also seems to count usages in older revisions. So to be absolutely sure an image may safely be removed isn't easy if it's still in use by an older revision.

It would be an option to make it so that it only shows the usage from current revisions only, but than we couldn't use the revision history with assets if we removed the 'unused' assets that were in use in those revisions.

So my request is to have an extra column 'Current Usage' that only counts the usage of the asset in all current versions, so doesn't count the usage in older revisions.
This would be really helpful and actually very important to be sure an image can be removed if it's not in use by the current versions. And with these two columns 'Usage' and 'Current Usage' we could also see very clearly that an image is only used in a previous revision so we can make our own decisions based on that whether or not we'd like to remove an asset.

Would be great. Thanks a lot in advance! ;)

[edit] I would also count drafts to the 'current usage' as these are about to go live

**Comment by roelvanhintum** [comment]
@Friksel i've just released 2.2.0 with the new current usage column.
