### ISSUE TITLE
Feature Request: Don't mark "originals" as "unused" if there is a transformed copy if it

### ISSUE THREAD

**Issue by mizziness** [born05/craft-assetusage#23]
The plugin [Plugin Resizer](https://plugins.craftcms.com/image-resizer) has a "non-destructive" option that creates a folder in each volume called "originals". 

**Desired Behavior:**

User has the ability to ignore "originals" (or even whole folders when checking for unused assets.)

**Current Behavior:**

This plugin currently counts original files as "Unused" even if there is a generated "child" image. It would be ideal if "originals" files were only marked as Unused if they do not have a child copy currently in use.

**Comment by roelvanhintum** [comment]
@mizziness this feels like misuse of the assets system, but i'm not familiar with that plugin.
Do the assets keep any relation with the smaller images? If there is any relationship, i could use that to show usage numbers.

**Comment by mizziness** [comment]
@roelvanhintum I'm only a user of the other plugin, not a maintainer, so I don't know if a relationship is maintained. I would *hope* so, but I would hope a lot of things that aren't so.

**Comment by roelvanhintum** [comment]
@mizziness Looking at [their code](https://github.com/verbb/image-resizer/blob/fc8d8316cf139845b07dee8682dd5623c2778936/src/services/Resize.php#L70), they don't keep any relation. This would mean an extra query for every asset to see if there is a file with the same name in `originals`.

**Comment by mizziness** [comment]
@roelvanhintum  Let me know if I can be of any help!
