### ISSUE TITLE
Custom language for "Current Usage"

### ISSUE THREAD

**Issue by chadcrowell** [born05/craft-assetusage#24]
When displaying the current usage column in a list of assets, it just takes up a lot of room horizontally. While the usage count just takes up 1 or 2 digits, "Current Usage" is 13. I'd like a setting to be able to change the column header. In my case I just want it to be "U" to take up as little horizontal space as possible.

**Comment by roelvanhintum** [comment]
@chadcrowell the labels are a bit large. Do you think naming the columns "Used" and "In use" will be better and still clear enough? And naming the values "{count} times"?

**Comment by chadcrowell** [comment]
Ideally, I think a plugin setting for the column label would be the best, maybe with a default of "Usage" (for American english, anyway, that would be the shortest term that makes sense with just the count in the table). If you don't want to provide a setting than "Usage" would be my preference, and just the count in the table as it currently is.

**Comment by roelvanhintum** [comment]
@chadcrowell, there are 2 types of columns with different numbers, which is why i'm trying to label only one as "Usage".
Currently the numbers are rendered as "Used {count} times", so i don't know why you are seeing just the numbers. You can change all texts from your own translations folder, which is why i'm reluctant with adding a setting for labels.

I was thinking about changing to the following labels, can you give your opinion on this?
```
'Used' // Old usage table
'{count} time' and '{count} times' // are the time/times additions nedded?
'Unused' // should this be just 0?
'In use' // Could be Usage, anyway this is the current column
```

**Comment by chadcrowell** [comment]
I never noticed there were 2 columns available via your plugin. Showing them both here: https://d.pr/i/0DaIli - I guess the one already says "Usage". I had only previously enabled the "Current Usage" column and never noticed the other one. What is the difference between them?

**Comment by chadcrowell** [comment]
OK re-read the docs... got it. "The "Usage" field shows all relations and the "Current Usage" field shows relations excluding revisions and deleted elements." Honestly I just need the Current Usage field and would like that label to be shorter... but I think you got that from my initial request.

Maybe Total Usage & Live Usage would be appropriate?
