### ISSUE TITLE
Craft 4?

### ISSUE THREAD

**Issue by angieherrera** [born05/craft-assetusage#29]
Wondering if this plugin will get updated for Craft 4?

**Comment by janhenckens** [comment]
Minimal changes required for this, made PR [here](https://github.com/born05/craft-assetusage/pull/30)

**Comment by roelvanhintum** [comment]
Yes, it will be. Thanks @janhenckens! I'll try to look into it this week.

**Comment by roelvanhintum** [comment]
@angieherrera, we've just released 3.0.0-beta.1
Please let me know if you run into any issues.
