### ISSUE TITLE
Poor performance

### ISSUE THREAD

**Issue by thisisjamessmith** [born05/craft-assetusage#32]
Enabling the plugin and switching on the usage columns causes the asset index screens to load very slowly.

**Comment by roelvanhintum** [comment]
Hi @thisisjamessmith the plugin needs to run queries for every asset to check usage. This will always be slower than not doing that. Having that said, in my experience this only makes a slight difference. Can you share some info on version numbers of Craft, the plugin and php?

**Comment by philippe-leeroy** [comment]
Same for us with 

PHP: 8.2.2
CraftCMS: Craft Pro 4.4.6

We have about 400 assets on our project...

Plus, we have a folder - with svg files - that never load when this plugin was activated.
