### ISSUE TITLE
Used assets show up as unused

### ISSUE THREAD

**Issue by HannahDeWachter** [born05/craft-assetusage#34]
### Situation
When an asset is selected in following field: Matrix block -> [SuperTable](https://github.com/verbb/super-table) -> [CTA](https://github.com/statikbe/craft-ctafield), it shows up as unused in the assets overview.
<img width="709" alt="Screenshot 2022-07-04 at 08 24 20" src="https://user-images.githubusercontent.com/55497252/177096922-946f67f4-50ea-4885-b72f-e2c395cbffea.png">
<img width="919" alt="Screenshot 2022-07-04 at 08 24 55" src="https://user-images.githubusercontent.com/55497252/177096929-74f7f0ef-e94c-4226-b4c0-d01cdea395a2.png">

#### Versions
Craft: 3.7.34
Asset Usage: 2.2.1

**Comment by roelvanhintum** [comment]
@HannahDeWachter it looks like the CTA field doesn't use Craft's relations table, but instead stores everything in its own field data. This makes it impossible to find asset relations with reasonable performance.
