### ISSUE TITLE
Assets still listed in Asset browser

### ISSUE THREAD

**Issue by sg-modlab** [born05/craft-assetusage#37]
First, thanks for creating and making available the unused asset plugin for Craft. Was trying this out on a project, and notice that the CLI deletion of unused assets did work in terms of deleting the files; however, in craft, I am still seeing the assets listed in the Asset browser. I tried clearing cache and rebuilding asset index but no change. Any ideas?

Craft CMS 4.4.5
Asset Usage 3.0.0

**Comment by roelvanhintum** [comment]
Hi @sg-modlab, the deletion itself is done in the same way as Craft's assets controller. So, maybe cache? Did you check the error log?
