### ISSUE TITLE
Neo Plugin Fix

### ISSUE THREAD

**Issue by websNL** [born05/craft-assetusage#4]
Hi,

We're using the plugin Neo: https://github.com/benjamminf/craft-neo
It has another element type on which the usage can relate to.

Can you add support for that plugin too?
We already fixed it, but we can't create a pull request for it.

Add on line 42:

`// In case of Neo plugin
$relatedAssetIds = array_merge($relatedAssetIds, $this->getAllElementsOfType('Neo_Block'));
`

Thanks!

**Comment by roelvanhintum** [comment]
No problem. Next time, feel free to create a pull-request.

**Comment by websNL** [comment]
Geachte relatie,

Welkom bij de servicedesk van Webs. Voor vragen, bugs en wijzigingen aan uw
website of hosting pakket, kunt u gebruik maken van dit Servicedesk
systeem.

Nadat een project of service is opgeleverd zijn er vaak nog veel
aanvullende vragen. Om efficiënt antwoord te kunnen geven op deze vragen
werken we met de Webs Servicedesk. Jij kunt met een eigen account 24-uur
per dag al je vragen en wensen insturen. Doordat je deze instuurt via de
Servicedesk kunnen wij aan onze kant deze vragen efficiënt oppakken door
ze direct bij de juiste mensen neer te leggen. 

*De voordelen van de Webs Servicedesk*
- 24/7 bereikbaar
- Vragen worden sneller opgepakt en beantwoord 
- Inzage in de status van je vraag

*Hoe maak je gebruik van de Webs Servicedesk?*
Voordat je gebruik kunt maken van de Servicedesk is het belangrijk om eerst
even je account te activeren. Dit kun je doen via deze link:
https://websnl.teamwork.com/support/#resetpassword/282461:69c4e7e9-d7df-4b71-8acb-d4515c891e44:372013.
Nadat je account is geactiveerd kun je gebruik maken van deze dienst door
een e-mail met je vragen te sturen naar support@webs.nl
<mailto:support@webs.nl> of via de website
https://websnl.teamwork.com/support.

Met vriendelijke groet,

Servicedesk medewerkers van Webs
040 2324611
support@webs.nl <mailto:support@webs.nl>

**Comment by websNL** [comment]
Geachte relatie,

Welkom bij de servicedesk van Webs. Voor vragen, bugs en wijzigingen aan uw
website of hosting pakket, kunt u gebruik maken van dit Servicedesk
systeem.

Nadat een project of service is opgeleverd zijn er vaak nog veel
aanvullende vragen. Om efficiënt antwoord te kunnen geven op deze vragen
werken we met de Webs Servicedesk. Jij kunt met een eigen account 24-uur
per dag al je vragen en wensen insturen. Doordat je deze instuurt via de
Servicedesk kunnen wij aan onze kant deze vragen efficiënt oppakken door
ze direct bij de juiste mensen neer te leggen. 

*De voordelen van de Webs Servicedesk*
- 24/7 bereikbaar
- Vragen worden sneller opgepakt en beantwoord 
- Inzage in de status van je vraag

*Hoe maak je gebruik van de Webs Servicedesk?*
Voordat je gebruik kunt maken van de Servicedesk is het belangrijk om eerst
even je account te activeren. Dit kun je doen via deze link:
https://websnl.teamwork.com/support/#resetpassword/282461:3e913f04-bb9e-4e56-b1c6-b80ec3df5823:372015.
Nadat je account is geactiveerd kun je gebruik maken van deze dienst door
een e-mail met je vragen te sturen naar support@webs.nl
<mailto:support@webs.nl> of via de website
https://websnl.teamwork.com/support.

Met vriendelijke groet,

Servicedesk medewerkers van Webs
040 2324611
support@webs.nl <mailto:support@webs.nl>

**Comment by roelvanhintum** [comment]
^ this

**Comment by websNL** [comment]
Geachte relatie,

Welkom bij de servicedesk van Webs. Voor vragen, bugs en wijzigingen aan uw
website of hosting pakket, kunt u gebruik maken van dit Servicedesk
systeem.

Nadat een project of service is opgeleverd zijn er vaak nog veel
aanvullende vragen. Om efficiënt antwoord te kunnen geven op deze vragen
werken we met de Webs Servicedesk. Jij kunt met een eigen account 24-uur
per dag al je vragen en wensen insturen. Doordat je deze instuurt via de
Servicedesk kunnen wij aan onze kant deze vragen efficiënt oppakken door
ze direct bij de juiste mensen neer te leggen. 

*De voordelen van de Webs Servicedesk*
- 24/7 bereikbaar
- Vragen worden sneller opgepakt en beantwoord 
- Inzage in de status van je vraag

*Hoe maak je gebruik van de Webs Servicedesk?*
Voordat je gebruik kunt maken van de Servicedesk is het belangrijk om eerst
even je account te activeren. Dit kun je doen via deze link:
https://websnl.teamwork.com/support/#resetpassword/282461:a00ea2a2-5ac0-40c7-a50e-2671b01ec071:372016.
Nadat je account is geactiveerd kun je gebruik maken van deze dienst door
een e-mail met je vragen te sturen naar support@webs.nl
<mailto:support@webs.nl> of via de website
https://websnl.teamwork.com/support.

Met vriendelijke groet,

Servicedesk medewerkers van Webs
040 2324611
support@webs.nl <mailto:support@webs.nl>
