### ISSUE TITLE
Amazon S3 objects count doubled after installing this plugin

### ISSUE THREAD

**Issue by dan3e** [born05/craft-assetusage#41]
Our Amazon S3 Bucket almost doubled (from 4719 objects to 7959) after installing this plugin (installed on March 5). Is the plugin creating thumbnail images? It also affects our usage on Imgix and we had to increase our plan. 

<img width="901" alt="Screenshot 2024-03-18 at 9 00 29 AM" src="https://github.com/born05/craft-assetusage/assets/115178377/1c482e89-58fc-4ec9-ad55-384720b6a943">

**Comment by roelvanhintum** [comment]
Hi @dan3e, the plugin does not create images. We basically just query the relations table. Could the images come from Craft's asset overview? Or maybe another change that happened at the same time?
