### ISSUE TITLE
Chore - Adjust composer.json to require CraftV 5.0.0

### ISSUE THREAD

**Issue by FabioDiCeglie** [born05/craft-assetusage#45]
# Summary:
Update the composer.json file to set the required version of Craft CMS to `5.0.0`, replacing the current requirement of `5.0.0-beta.1`.

# Description:
The current composer.json specifies Craft CMS version 5.0.0-beta.1 as a dependency. With the stable release of Craft CMS 5.0.0, we need to update the dependency to ensure that our project uses the latest stable version.

This task involves modifying the composer.json file to require "craftcms/cms": "^5.0.0" and ensuring that the application functions correctly with this version.

# Acceptance Criteria:
Update the composer.json file to reflect `"craftcms/cms": "^5.0.0"` in the require section.
Run composer update to ensure dependencies are resolved correctly.
Verify that the project runs smoothly with Craft CMS 5.0.0 and that all existing functionality is intact.

**Comment by FabioDiCeglie** [comment]
PR #46

**Comment by roelvanhintum** [comment]
Thank you! Released as 4.1.3
