### ISSUE TITLE
Dosn't recognise assets when ussed in seoMatic Plugin

### ISSUE THREAD

**Issue by kaspar-allenbach** [born05/craft-assetusage#5]
On Craft 2.6.2017
Asset Usage 1.0.2
SEOmatic 1.1.56

**Comment by roelvanhintum** [comment]
True. Most plugins with custom fields probably won't work. Only SuperTable, Neo and FocusPoint works. I'll put this on the to list.

**Comment by kaspar-allenbach** [comment]
It is such a useful plugin. My chaotic clients love it. 👍

**Comment by roelvanhintum** [comment]
@kaspar-allenbach, just released the Craft 3 plugin as a beta. This one just checks the relations table, which covers SeoMatic and any other plugin using assets in the right way.
It should also be a lot quicker than the Craft 2 plugin.
