### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by j2is** [born05/craft-assetusage#7]
I tried to install using the plugin store but it didn't work and didnt generate an error. Alternatively I tried `composer require born05/craft-assetusage` but receive an error `The requested package born05/craft-assetusage could not be found in any version, there may be a typo in the package name`. I had a look on Packagist and could not find it listed

**Comment by roelvanhintum** [comment]
@j2is I just tried to install with success on Craft 3.0.26.1. The package isn't on Packagist so that won't work. If you must, you can add the repository to your composer file.
Did you check the storage/logs for any errors?
