### ISSUE TITLE
Not seeing relations from a linkit field

### ISSUE THREAD

**Issue by bartrylant** [born05/craft-assetusage#8]
I know this is probably not a situation that's quite common, but when you're using a field from the Linkit (plugin) type and you link to an asset, this asset is labeled as "not used", while in fact, it is being used.

**Comment by roelvanhintum** [comment]
@bartrylant Thanks! I'll look into it. Looks like they don't use the relations table, but the contents table, where they store a serialized object. This would involve giant queries on content, matrixcontent and supertablecontent and some processing to determine the usage of an asset.

https://github.com/fruitstudios/craft-linkit/blob/master/src/fields/LinkitField.php#L131

**Comment by roelvanhintum** [comment]
Just created an issue. Hopefully they are willing to change: https://github.com/fruitstudios/craft-linkit/issues/40
