### ISSUE TITLE
Show only unused Images

### ISSUE THREAD

**Issue by davidhellmann** [born05/craft-assetusage#9]
Is there a way to make that happen to delete some image? We have round about 5k images in craft and delete every image manually is not really a fast way  : )

**Comment by roelvanhintum** [comment]
This requires registering the usage column as sortable. I'll look into this.

**Comment by davidhellmann** [comment]
That would be really awesome! Thanks!!

**Comment by roelvanhintum** [comment]
@davidhellmann Please be careful with deleting assets. Some field types may not work in combination with this plugin. For example, seoMatic doesn't work with this plugin because they store relations in a different place than usual.

**Comment by davidhellmann** [comment]
OK, thanks for the info!

**Comment by KatieMFritz** [comment]
@roelvanhintum Is the information here all still accurate with the current version of the plugin, or does it have more capabilities now?
